zone_nfreq: [16384]
zone_freq_edges: [400, 800]
tree_rank: 15
num_downsampling_levels: 4
time_samples_per_chunk: 2048
dtype: float16
early_triggers:
  []
frequency_subband_counts: [1]
peak_finding_params:
  - {max_width: 16, dm_downsampling: 0, time_downsampling: 0, wt_dm_downsampling: 64, wt_time_downsampling: 64}
  - {max_width: 16, dm_downsampling: 0, time_downsampling: 0, wt_dm_downsampling: 64, wt_time_downsampling: 64}
  - {max_width: 16, dm_downsampling: 0, time_downsampling: 0, wt_dm_downsampling: 64, wt_time_downsampling: 64}
  - {max_width: 16, dm_downsampling: 0, time_downsampling: 0, wt_dm_downsampling: 64, wt_time_downsampling: 64}
beams_per_gpu: 100
beams_per_batch: 2
num_active_batches: 2