zone_nfreq: [16384]
zone_freq_edges: [400, 800]
time_sample_ms: 1.0
tree_rank: 15
num_downsampling_levels: 4
time_samples_per_chunk: 2048
dtype: float16

# No early triggers.
early_triggers: []

# python -m pirate_frb show_subbands --rank=4 --fmin=400 --fmax=800 --threshold=0.1
frequency_subband_counts: [0,5,7,3,1]

# FIXME peak_finding_params are not quite right (same params at each level)
peak_finding_params:
  - {max_width: 16, dm_downsampling: 0, time_downsampling: 0, wt_dm_downsampling: 64, wt_time_downsampling: 64}
  - {max_width: 16, dm_downsampling: 0, time_downsampling: 0, wt_dm_downsampling: 64, wt_time_downsampling: 64}
  - {max_width: 16, dm_downsampling: 0, time_downsampling: 0, wt_dm_downsampling: 64, wt_time_downsampling: 64}
  - {max_width: 16, dm_downsampling: 0, time_downsampling: 0, wt_dm_downsampling: 64, wt_time_downsampling: 64}

# FIXME placeholder: only 10 beams/GPU.
beams_per_gpu: 10
beams_per_batch: 2
num_active_batches: 2